### ISSUE TITLE
似乎并没有提供对labelcategory和Connectioncategory的增删改查操作？

### ISSUE THREAD

**Issue by VelikayaScarlet** [synyi/poplar#143]
vue.esm.js:591  [Vue warn]: Error in event handler for "click": "TypeError: Cannot read properties of undefined (reading 'trim')"

found in

---> <VBtn>
       <VCard>
         <VDialog>
           <Demo> at src\components\Demo.vue
             <VApp>
               <App> at src\App.vue
                 <Root>
warn @ vue.esm.js:591
logError @ vue.esm.js:1737
globalHandleError @ vue.esm.js:1732
handleError @ vue.esm.js:1721
Vue.$emit @ vue.esm.js:2540
click @ vuetify.js:1363
invoker @ vue.esm.js:2027
fn._withTask.fn._withTask @ vue.esm.js:1826
vue.esm.js:1741  TypeError: Cannot read properties of undefined (reading 'trim')
    at t.construct (index.js:16:1)
    at t.set [as json] (index.js:16:1)
    at VueComponent.addLabel (Demo.vue:329:1)
    at VueComponent.invoker (vue.esm.js:2027:1)
    at Vue.$emit (vue.esm.js:2538:1)
    at VueComponent.click (vuetify.js:1363:1)
    at invoker (vue.esm.js:2027:1)
    at fn._withTask.fn._withTask (vue.esm.js:1826:1)
logError @ vue.esm.js:1741
globalHandleError @ vue.esm.js:1732
handleError @ vue.esm.js:1721
Vue.$emit @ vue.esm.js:2540
click @ vuetify.js:1363
invoker @ vue.esm.js:2027
fn._withTask.fn._withTask @ vue.esm.js:1826

**Comment by VelikayaScarlet** [comment]
已解决
            addLabel: function() {
              let jsonData = JSON.stringify(this.annotator.store.json, null, 2);
              let list = JSON.parse(jsonData);
              const newLabelCategory = {
                id: list.labelCategories.length,
                text: this.addLabelText,
                color: this.getRandomColor(),
                borderColor: this.getRandomColor()
              };
              this.annotator.store.labelCategoryRepo.add(newLabelCategory)
              this.getCode()
            },

**Comment by VelikayaScarlet** [comment]
addLabel: function() {
              let newID = -1;
              for (let [_, category] of this.annotator.store.labelCategoryRepo) {
                  newID = category["id"]+1
              }
              const newLabelCategory = {
                id: newID, 
                text: this.addLabelText,
                color: this.getRandomColor(),
                borderColor: this.getRandomColor()
              };
              this.annotator.store.labelCategoryRepo.add(newLabelCategory)
              console.log(this.labelCategories);
              this.getCode()
            },
